### ISSUE TITLE
Can we add tenv?

### ISSUE THREAD

**Issue by kvendingoldo** [wmariuss/awesome-devops#154]
https://github.com/tofuutils/tenv  is OpenTofu, Terraform, Terragrunt, and Atmos version manager, written in Go. For now it's the only one version manager that smartly support OpenTofu/Terraform/Terragrunt and Atmos in one tool.

**Comment by wmariuss** [comment]
Hi,

Thank you for your suggestion. Sure, we can add it.

**Comment by kvendingoldo** [comment]
@wmariuss review pls : https://github.com/wmariuss/awesome-devops/pull/163

**Comment by wmariuss** [comment]
Thanks. Closing the issue.
