### ISSUE TITLE
Addition of Nix and / or NixOS

### ISSUE THREAD

**Issue by JustAlternate** [wmariuss/awesome-devops#202]
Hi everyone, I was wondering if Nix / NixOS could be a great addition to this awesome list ?

Nix is a declarative package manager that can be used to make reproducible dev environment.
And NixOS is a Linux distribution that embrace the system as code approach to making reproducible system configuration.

Nowadays, Nix comes with a very wide and growing ecosystem which make it a usable tool for DevOps engineer.

**Comment by wmariuss** [comment]
Hi,

That a good tool to add. Thanks.

**Comment by wmariuss** [comment]
Added, thanks.
